server:
  port: 80
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/full_contact_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

app:
  security:
    username: Admin
    password: 12563Aas@